#!/bin/bash

# Run this file in a terminal to obtain the data required to recreate Figure 3 of the manuscript.

julia --project --threads=auto CalculationCode/replicator_mutator_emergence_patterns.jl --switch_guess_points=false --neighbours=16 --savefile figure_3_results