#!/bin/bash

# Run this file in a terminal to obtain the data required to recreate Figure S3 of the manuscript.

julia --project --threads=auto CalculationCode/replicator_mutator_emergence_patterns.jl --w_begin=0.1 --w_end=0.1 --neighbours=40 --problem_area_number=3 --savefile figure_S3A_results

julia --project --threads=auto CalculationCode/replicator_mutator_emergence_patterns.jl --w_begin=0.4 --w_end=0.4 --neighbours=40 --problem_area_number=3 --savefile figure_S3B_results

julia --project --threads=auto CalculationCode/replicator_mutator_emergence_patterns.jl --w_begin=0.6 --w_end=0.6 --neighbours=40 --problem_area_number=3 --savefile figure_S3C_results